### ISSUE TITLE
Incompatibility with Floodgate plugin

### ISSUE THREAD

**Issue by kolderz** [adde0109/Ambassador#10]
Is there a way to ignore Floodgate, because floodgate makes Ambassador not work correctly?

```
ERROR]: Couldn't pass ProxyInitializeEvent to ambassador
--
2 | java.lang.ClassCastException: class org.geysermc.floodgate.inject.velocity.VelocityInjector$VelocityChannelInitializer cannot be cast to class com.velocitypowered.proxy.network.ServerChannelInitializer (org.geysermc.floodgate.inject.velocity.VelocityInjector$VelocityChannelInitializer is in unnamed module of loader com.velocitypowered.proxy.plugin.PluginClassLoader @67e28be3; com.velocitypowered.proxy.network.ServerChannelInitializer is in unnamed module of loader 'app')
3 | at org.adde0109.ambassador.Ambassador.inject(Ambassador.java:65) ~[?:?]
4 | at org.adde0109.ambassador.Ambassador.onProxyInitialization(Ambassador.java:57) ~[?:?]
5 | at org.adde0109.ambassador.Lmbda$1.execute(Unknown Source) ~[?:?]
6 | at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity-3.1.2-SNAPSHOT-184.jar:3.1.2-SNAPSHOT (git-7d77bfb5-b184)]
7 | at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity-3.1.2-SNAPSHOT-184.jar:3.1.2-SNAPSHOT (git-7d77bfb5-b184)]
8 | at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity-3.1.2-SNAPSHOT-184.jar:3.1.2-SNAPSHOT (git-7d77bfb5-b184)]
9 | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
10 | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
11 | at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by adde0109** [comment]
The issue should be resolved with the release of 1.1.7-alpha.
