### ISSUE TITLE
Error when connecting to ChromaSky2 1.16.5 modpack

### ISSUE THREAD

**Issue by Longtianmu** [adde0109/Ambassador#2]
`[23:06:54 INFO]: [server connection] Longtianmu -> chromasky2 has connected
[23:06:55 ERROR]: [server connection] Longtianmu -> chromasky2: exception encountered in com.velocitypowered.proxy.connection.backend.LoginSessionHandler@4b57b34f
>io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Unable to find id for packet of type com.velocitypowered.proxy.protocol.packet.PluginMessage in SERVERBOUND protocol 1.16.4
at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:110) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at com.velocitypowered.proxy.connection.MinecraftConnection.write(MinecraftConnection.java:218) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at com.velocitypowered.proxy.connection.client.InitialConnectSessionHandler.handle(InitialConnectSessionHandler.java:49) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at com.velocitypowered.proxy.protocol.packet.PluginMessage.handle(PluginMessage.java:104) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:142) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:89) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:58) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at java.lang.Thread.run(Thread.java:833) [?:?]
>Caused by: java.lang.IllegalArgumentException: Unable to find id for packet of type com.velocitypowered.proxy.protocol.packet.PluginMessage in SERVERBOUND protocol 1.16.4
at com.velocitypowered.proxy.protocol.StateRegistry$PacketRegistry$ProtocolRegistry.getPacketId(StateRegistry.java:469) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at com.velocitypowered.proxy.protocol.netty.MinecraftEncoder.encode(MinecraftEncoder.java:49) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at com.velocitypowered.proxy.protocol.netty.MinecraftEncoder.encode(MinecraftEncoder.java:29) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
... 55 more`

**Comment by Longtianmu** [comment]
![image](https://user-images.githubusercontent.com/60567448/178150980-1081c692-8ea5-41b4-8a04-bb12d6178692.png)

**Comment by adde0109** [comment]
How do I reproduce this error?

**Comment by adde0109** [comment]
I tried to reproduce it. Didn't encounter the issue that's described here. I connected successfully to a Chroma Sky 2 server using Velocity and Ambassador.

**Comment by Longtianmu** [comment]
> I tried to reproduce it. Didn't encounter the issue that's described here. I connected successfully to a Chroma Sky 2 server using Velocity and Ambassador.

Which server do you use?
I use Mohist/Arclight,but all failed

**Comment by Longtianmu** [comment]
Also,I use legacy forwarding

**Comment by adde0109** [comment]
Does it work when legacy forwarding is turned off?

**Comment by Longtianmu** [comment]
well, modern forwarding will break 1.12.2 forge server, and that's what I need

**Comment by adde0109** [comment]
If you can, you could instead try to use Lightfall (A waterfall fork) which is a recommended proxy for Arclight.

I will try to look into the issue more tomorrow.

**Comment by adde0109** [comment]
I have tested Chroma Sky 2 using Arclight with Legacy Forwarding.

No errors found and things works as expected. 
![bild](https://user-images.githubusercontent.com/52883522/178329461-4cbe22a9-7256-468b-9f99-409a4471292a.png)

**Comment by Longtianmu** [comment]
> I have tested Chroma Sky 2 using Arclight with Legacy Forwarding.
> 
> No errors found and things works as expected. ![bild](https://user-images.githubusercontent.com/52883522/178329461-4cbe22a9-7256-468b-9f99-409a4471292a.png)
> 
> * Using Java 11
> * Using latest forge version: 36.2.35
> * Removed server-side mod RoadRunner because of crashing when trying to start server.

Could I take a look of your VelocitySide Config?
I also install ViaVersion and ViaBackwards. Could they cause this problem?
@adde0109

**Comment by adde0109** [comment]
I'm using the default velocity config with the forwading set to "legacy". Delete it to get the defult one.

ViaVersion and ViaBackwards works. 
Note: You cant join vanilla with the Chorma Sky 2 modpack installed on your client, some mods does not allow vanilla connections. So make sure you go straight to the forge server when connecting. You could set the "force" field to true in Ambassador's config to ensure this.

**Comment by Longtianmu** [comment]
Today I test more and found some info.
I could join Chroma Sky 2, but only one times in lots trys.
Maybe it's cause by random packet loss because I used Zerotier(UDP) to connect Velocity with backend servers.
When I set network-compression-level to -1, it seems like works better.
Anyway, I am still confused with it.

**Comment by Longtianmu** [comment]
okay I need to say that the connection is totally random

**Comment by adde0109** [comment]
Can you try without Zeroteir?

**Comment by adde0109** [comment]
Also, do you get the same error every time?

**Comment by Longtianmu** [comment]
yeah I got same error every time

**Comment by Longtianmu** [comment]
> Can you try without Zeroteir?

Well except Zerotier, I don't know what to use

**Comment by adde0109** [comment]
Do you got any other plugins running on Velocity?

**Comment by Longtianmu** [comment]
![image](https://user-images.githubusercontent.com/60567448/178663684-70e22be4-4ad7-4a5d-9aed-81b2e8848581.png)
btw, I use the build on papermc.io

**Comment by adde0109** [comment]
My theory is that mods on the client starts sending plugin messages before the backend server is connected. In other words, the client gets ready faster than the backend server. I could try tom simulate a slow connecting backend server yo try to reproduce it.

**Comment by adde0109** [comment]
I'm opening this again.

**Comment by Longtianmu** [comment]
Maybe the login packet is randomly losed.
Do re-sending more packets work?

**Comment by adde0109** [comment]
Even though ZeroTeir is UDP, the Minecraft connection is still tcp. So i think ZeroTeir automatically resends the packets that get lost.

I just consulted Velocity's source code and is 70% sure the problem is that the connection between Velocity sn backend server is slow sometimes
That also explains why it's random and you can connect sometimes.

**Comment by adde0109** [comment]
I will look into it more tomorrow, but i think it's fixable.

**Comment by Longtianmu** [comment]
Then is wireguard helpful?
Zerotier has a random ping-time increase, like this packet is 25ms and next is 631ms

**Comment by adde0109** [comment]
You could try. But if it turns out that i can fix it in Ambassador, I will. 
I don't want a slow connection to stop anyone from connecting.

**Comment by adde0109** [comment]
Update: I have been in contact with one of the devs for Velocity and they will fix this problem in the future. In the meantime I suggest you run the proxy on the same machine as the forge server or find a way to faster connect to the forge server.
