### ISSUE TITLE
Cannot connect to server: Identifier is empty.

### ISSUE THREAD

**Issue by dsx137** [adde0109/Ambassador#57]
## Environment

velocity: velocity-3.3.0-SNAPSHOT-393.jar  
velocity plugins:  Ambassador-Velocity-1.4.4-all.jar  
velocity mode: legacy (and modern also)

backend: mohist-1.18.2-173-server.jar (and arclight-forge-1.18.2-1.0.12.jar also)  
backend plugins: None  
backend modpack: https://www.curseforge.com/minecraft/modpacks/atlanabyss

---

## Error

```java
// Velocty

[18:25:52 ERROR]: [connected player] RTomsk (/192.168.2.15:35470): exception encountered in com.velocitypowered.proxy.connection.client.InitialConnectSessionHandler@60aae253
io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Identifier is empty.
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[velocity-3.3.0-SNAPSHOT-393.jar:3.3.0-SNAPSHOT (git-42d42883-b393)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.3.0-SNAPSHOT-393.jar:3.3.0-SNAPSHOT (git-42d42883-b393)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-393.jar:3.3.0-SNAPSHOT (git-42d42883-b393)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-393.jar:3.3.0-SNAPSHOT (git-42d42883-b393)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:92) ~[velocity-3.3.0-SNAPSHOT-393.jar:3.3.0-SNAPSHOT (git-42d42883-b393)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:61) ~[velocity-3.3.0-SNAPSHOT-393.jar:3.3.0-SNAPSHOT (git-42d42883-b393)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.3.0-SNAPSHOT-393.jar:3.3.0-SNAPSHOT (git-42d42883-b393)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-393.jar:3.3.0-SNAPSHOT (git-42d42883-b393)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-393.jar:3.3.0-SNAPSHOT (git-42d42883-b393)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity-3.3.0-SNAPSHOT-393.jar:3.3.0-SNAPSHOT (git-42d42883-b393)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.3.0-SNAPSHOT-393.jar:3.3.0-SNAPSHOT (git-42d42883-b393)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-393.jar:3.3.0-SNAPSHOT (git-42d42883-b393)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-393.jar:3.3.0-SNAPSHOT (git-42d42883-b393)]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity-3.3.0-SNAPSHOT-393.jar:3.3.0-SNAPSHOT (git-42d42883-b393)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity-3.3.0-SNAPSHOT-393.jar:3.3.0-SNAPSHOT (git-42d42883-b393)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-393.jar:3.3.0-SNAPSHOT (git-42d42883-b393)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-393.jar:3.3.0-SNAPSHOT (git-42d42883-b393)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity-3.3.0-SNAPSHOT-393.jar:3.3.0-SNAPSHOT (git-42d42883-b393)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[velocity-3.3.0-SNAPSHOT-393.jar:3.3.0-SNAPSHOT (git-42d42883-b393)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.3.0-SNAPSHOT-393.jar:3.3.0-SNAPSHOT (git-42d42883-b393)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-393.jar:3.3.0-SNAPSHOT (git-42d42883-b393)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-393.jar:3.3.0-SNAPSHOT (git-42d42883-b393)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity-3.3.0-SNAPSHOT-393.jar:3.3.0-SNAPSHOT (git-42d42883-b393)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity-3.3.0-SNAPSHOT-393.jar:3.3.0-SNAPSHOT (git-42d42883-b393)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-393.jar:3.3.0-SNAPSHOT (git-42d42883-b393)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity-3.3.0-SNAPSHOT-393.jar:3.3.0-SNAPSHOT (git-42d42883-b393)]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[velocity-3.3.0-SNAPSHOT-393.jar:3.3.0-SNAPSHOT (git-42d42883-b393)]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[velocity-3.3.0-SNAPSHOT-393.jar:3.3.0-SNAPSHOT (git-42d42883-b393)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[velocity-3.3.0-SNAPSHOT-393.jar:3.3.0-SNAPSHOT (git-42d42883-b393)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.3.0-SNAPSHOT-393.jar:3.3.0-SNAPSHOT (git-42d42883-b393)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.3.0-SNAPSHOT-393.jar:3.3.0-SNAPSHOT (git-42d42883-b393)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.3.0-SNAPSHOT-393.jar:3.3.0-SNAPSHOT (git-42d42883-b393)]
        at java.base/java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalArgumentException: Identifier is empty.
        at com.velocitypowered.api.proxy.messages.MinecraftChannelIdentifier.from(MinecraftChannelIdentifier.java:78) ~[velocity-3.3.0-SNAPSHOT-393.jar:3.3.0-SNAPSHOT (git-42d42883-b393)]
        at org.adde0109.ambassador.forge.packet.ModListReplyPacket.read(ModListReplyPacket.java:45) ~[?:?]
        at org.adde0109.ambassador.forge.pipeline.ForgeLoginWrapperDecoder.decode(ForgeLoginWrapperDecoder.java:35) ~[?:?]
        at org.adde0109.ambassador.forge.pipeline.ForgeLoginWrapperDecoder.decode(ForgeLoginWrapperDecoder.java:14) ~[?:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[velocity-3.3.0-SNAPSHOT-393.jar:3.3.0-SNAPSHOT (git-42d42883-b393)]
        ... 32 more
```

```java
// Mohist

[18:27:28 INFO]: com.mojang.authlib.GameProfile@3d9c282e[id=2023a329-6129-373b-827b-be15d324bf20,name=RTomsk,properties={extraData=[com.mojang.authlib.properties.Property@c547870]},legacy=false] (/192.168.2.15:46914) lost connection: Disconnected
```

---

Disconnected when try to connect server.

![图像_2024-05-27_182735415](https://github.com/adde0109/Ambassador/assets/70027572/cfb68365-7c1d-40fe-8b0f-c10aa780dc8a)

**Comment by dsx137** [comment]
Mod ModernUI's identifier path is empty, that's why.
I have contacted with the author to fix it.
